### ISSUE TITLE
My github accounts used for auth star-history-plugin

### ISSUE THREAD

**Issue by timqian** [timqian/my-notes#22]
https://github.com/timqian/star-history-plugin

**Comment by timqian1992** [comment]
9da45c0ed04c77c47278bb260d7c6b6c2c9b9fa8

**Comment by tim-qian** [comment]
d96ed1e68bec80e725db8f23327a96839def67a6

**Comment by timqian92** [comment]
569e1881d1b810c39e35c650f056ea6fac05a400

**Comment by timqian** [comment]
未加电场能带
![e0d 0 0 1 u](https://cloud.githubusercontent.com/assets/5512552/13765319/3783338e-ea93-11e5-9fc6-cb6ff79fea57.png)

E = 0.15
![e0 15d 0 0 1 u](https://cloud.githubusercontent.com/assets/5512552/13765358/a5c4fd1e-ea93-11e5-99ea-d7b2e7647dc5.png)

2.3  | 2.4 | 2.5 | 2.6 | 2.7 
---   |  --- | ---   |  --    | ---
-34.26 | -34.50 | -34.70 |-34.61 | -34.37

2.3 | 2.4 |2.5
------------ | -------------   | -----
Content from cell 1 | Content from cell 2 | 09

**Comment by timqian** [comment]
![screen shot 2016-03-16 at 09 54 47](https://cloud.githubusercontent.com/assets/5512552/13799745/5518f030-eb5d-11e5-8d5b-5005c77eea57.png)

**Comment by timqian** [comment]
![0](https://cloud.githubusercontent.com/assets/5512552/13802481/58fdb5ae-eb77-11e5-84bf-6a621384e918.png)
![0 05](https://cloud.githubusercontent.com/assets/5512552/13802482/5a7089e8-eb77-11e5-88d2-f37541910d1b.png)
![0 10](https://cloud.githubusercontent.com/assets/5512552/13802484/5bb6b354-eb77-11e5-877b-f9cf568f9ab3.png)
![0 15](https://cloud.githubusercontent.com/assets/5512552/13802488/5e9d8dd6-eb77-11e5-8bd9-96b752db083e.png)

**Comment by timqian** [comment]
![screen shot 2016-03-16 at 13 52 40](https://cloud.githubusercontent.com/assets/5512552/13803277/5f4df58e-eb7e-11e5-84d0-687224ffcef4.png)

**Comment by timqian** [comment]
![e0d 0 0 1 u](https://cloud.githubusercontent.com/assets/5512552/13812647/4c64c94a-ebb8-11e5-8359-36fdc08cf571.png)
![e0 15d 0 0 1 u](https://cloud.githubusercontent.com/assets/5512552/13812650/4f428148-ebb8-11e5-81f8-06e7c6960a08.png)

**Comment by timqian123** [comment]
31eee536d05b169b3e184e152d18775f7166123b

**Comment by timqian321** [comment]
da9f64e669b91d89f5abe19b313ab07a54b7c974

**Comment by timqian26** [comment]
ee3a172df9aaa8c858b5585ca53391cec47b20c0

**Comment by timqian** [comment]
![font](https://user-images.githubusercontent.com/5512552/58616539-806e8780-82f0-11e9-9b43-c73254a793db.png)
![font](https://user-images.githubusercontent.com/5512552/58616555-87959580-82f0-11e9-8ac4-4045463f2f41.png)
